In [3]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp<=theta:
        return 0
    elif tmp>theta:
        return 1

AND(1, 0)


0

In [3]:
def XAND(x1, x2):
    w1, w2, theta = -0.5, -0.5, -0.7
    tmp = x1*w1 + x2*w2
    if tmp<=theta:
        return 0
    elif tmp>theta:
        return 1

XAND(1, 0)


1

In [4]:
def OR(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.2
    tmp = x1*w1 + x2*w2
    if tmp<=theta:
        return 0
    elif tmp>theta:
        return 1

OR(0, 0) 
OR(1, 0)
OR(0, 1)
OR(1, 1)


1

In [1]:
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(x*w)+b
    if tmp <= 0:
        return 0
    else:
        return 1
    
    
ans = np.array([
  AND(0,0)
 ,AND(1,0)
 ,AND(0,1)
 ,AND(1,1)
])
ans

array([0, 0, 0, 1])

In [5]:
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.sum(x*w)+b
    if tmp <= 0:
        return 0
    else:
        return 1

ans = np.array([
  NAND(0,0)
 ,NAND(1,0)
 ,NAND(0,1)
 ,NAND(1,1)
])

ans

NameError: name 'np' is not defined

In [3]:
import numpy as np

def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = b + np.sum(x*w)
    if tmp <= 0:
        return 0
    else:
        return 1

ans = np.array([
  OR(0,0)
 ,OR(1,0)
 ,OR(0,1)
 ,OR(1,1)
])

ans

array([0, 1, 1, 1])

In [7]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

ans = np.array([
  XOR(0,0)
 ,XOR(1,0)
 ,XOR(0,1)
 ,XOR(1,1)
])
ans

array([0, 1, 1, 0])

In [7]:
def keisan(siki):
    if siki == "and":
        ans = np.array([AND(0,0),AND(1,0),AND(0,1),AND(1,1)])
    elif siki == "nand":
        ans = np.array([NAND(0,0),NAND(1,0),NAND(0,1),NAND(1,1)])
    elif siki == "or":
        ans = np.array([OR(0,0),OR(1,0),OR(0,1),OR(1,1)])
    elif siki == "xor": 
        ans == np.array([XOR(0,0),XOR(1,0),XOR(0,1),XOR(1,1)])
    else:
        ans = "error occured"
        
keisan(and)

SyntaxError: invalid syntax (922803377.py, line 13)